//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompetencyTrainingWebAPi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int AnswerID { get; set; }
        public string AnsDescription { get; set; }
        public int Score { get; set; }
        public Nullable<int> Employee_EmpID { get; set; }
        public Nullable<int> Question_QuestionID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Question Question { get; set; }
    }
}
